hl.config({ autogenerated = false })
local config = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
for _, name in ipairs({ "env", "general", "input", "devices", "rules", "execs", "keybinds" }) do
    dofile(config .. "/hypr/hyprland/" .. name .. ".lua")
end
